#include "quotes_helper.h"
#include <QApplication>
#include <QRandomGenerator>
#include <QVector>


QuotesHelper::Quote QuotesHelper::generateQuote(int _index)
{
    int index = 0;
    const QVector<Quote> quotes
              //
              // https://screencraft.org/2013/01/23/50-great-screenwriting-quotes/
              //
            = {{ index++, QApplication::translate("QuotesHelper", "Dialogue is a necessary evil."),
                 QApplication::translate("QuotesHelper", "Fred Zinnemann") },
               { index++, QApplication::translate("QuotesHelper", "The road to hell is paved with works-in-progress."),
                 QApplication::translate("QuotesHelper", "Philip Roth") },
               { index++, QApplication::translate("QuotesHelper", "There is only one plot—things are not what they seem."),
                 QApplication::translate("QuotesHelper", "Jim Thompson") },
               { index++, QApplication::translate("QuotesHelper", "The most beautiful things are those that madness prompts and reason writes."),
                 QApplication::translate("QuotesHelper", "Andre Gide") },
               { index++, QApplication::translate("QuotesHelper", "Literature is strewn with the wreckage of men who have minded beyond reason the opinions of others."),
                 QApplication::translate("QuotesHelper", "Virginia Woolf") },
               { index++, QApplication::translate("QuotesHelper", "If it sounds like writing, I rewrite it."),
                 QApplication::translate("QuotesHelper", "Elmore Leonard") },
               { index++, QApplication::translate("QuotesHelper", "Cinema should make you forget you are sitting in a theater."),
                 QApplication::translate("QuotesHelper", "Roman Polanski") },
               { index++, QApplication::translate("QuotesHelper", "Do not be told something is impossible. There is always a way."),
                 QApplication::translate("QuotesHelper", "Robert Rodriguez") },
               { index++, QApplication::translate("QuotesHelper", "My three Ps: passion, patience, perseverance. You have to do this if you’ve got to be a filmmaker."),
                 QApplication::translate("QuotesHelper", "Robert Wise") },
               { index++, QApplication::translate("QuotesHelper", "If it can be written, or thought, it can be filmed."),
                 QApplication::translate("QuotesHelper", "Stanley Kubrick") },
               { index++, QApplication::translate("QuotesHelper", "I became quite successful very young, and it was mainly because I was so enthusiastic and I just worked so hard at it."),
                 QApplication::translate("QuotesHelper", "Francis Ford Coppola") },
               { index++, QApplication::translate("QuotesHelper", "I steal from every movie ever made."),
                 QApplication::translate("QuotesHelper", "Quentin Tarantino") },
               { index++, QApplication::translate("QuotesHelper", "I don’t think screenplay writing is the same as writing — I mean, I think it’s blueprinting."),
                 QApplication::translate("QuotesHelper", "Robert Altman") },
               { index++, QApplication::translate("QuotesHelper", "The most ordinary word, when put into place, suddenly acquires brilliance. That is the brilliance with which your images must shine."),
                 QApplication::translate("QuotesHelper", "Robert Bresson") },
               { index++, QApplication::translate("QuotesHelper", "You sell a screenplay like you sell a car. If someone drives it off a cliff, that’s it."),
                 QApplication::translate("QuotesHelper", "Rita Mae Brown") },
               { index++, QApplication::translate("QuotesHelper", "A good film script should be able to do completely without dialogue."),
                 QApplication::translate("QuotesHelper", "David Mamet") },
               { index++, QApplication::translate("QuotesHelper", "To gain your own voice, you have to forget about having it heard."),
                 QApplication::translate("QuotesHelper", "Allen Ginsberg") },
               { index++, QApplication::translate("QuotesHelper", "Cheat your landlord if you can and must, but do not try to shortchange the Muse. It cannot be done. You can’t fake quality any more than you can fake a good meal."),
                 QApplication::translate("QuotesHelper", "William S. Burroughs") },
               { index++, QApplication::translate("QuotesHelper", "All readers come to fiction as willing accomplices to your lies. Such is the basic goodwill contract made the moment we pick up a work of fiction."),
                 QApplication::translate("QuotesHelper", "Steve Almond") },
               { index++, QApplication::translate("QuotesHelper", "It ain’t whatcha write, it’s the way atcha write it."),
                 QApplication::translate("QuotesHelper", "Jack Kerouac") },
               { index++, QApplication::translate("QuotesHelper", "Not a wasted word. This has been a main point to my literary thinking all my life."),
                 QApplication::translate("QuotesHelper", "Hunter S. Thompson") },
               { index++, QApplication::translate("QuotesHelper", "... don’t care if a reader hates one of my stories, just as long as he finishes the book."),
                 QApplication::translate("QuotesHelper", "Roald Dahl") },
               { index++, QApplication::translate("QuotesHelper", "We are all apprentices in a craft where no one ever becomes a master."),
                 QApplication::translate("QuotesHelper", "Ernest Hemingway") },
               { index++, QApplication::translate("QuotesHelper", "Every secret of a writer’s soul, every experience of his life, every quality of his mind, is written large in his works."),
                 QApplication::translate("QuotesHelper", "Virginia Woolf") },
               { index++, QApplication::translate("QuotesHelper", "If a nation loses its storytellers, it loses its childhood."),
                 QApplication::translate("QuotesHelper", "Peter Handke") },
               { index++, QApplication::translate("QuotesHelper", "Write. Rewrite. When not writing or rewriting, read. I know of no shortcuts."),
                 QApplication::translate("QuotesHelper", "Larry L. King") },
               { index++, QApplication::translate("QuotesHelper", "Know your literary tradition, savor it, steal from it, but when you sit down to write, forget about worshiping greatness and fetishizing masterpieces."),
                 QApplication::translate("QuotesHelper", "Allegra Goodman") },
               { index++, QApplication::translate("QuotesHelper", "Style is to forget all styles."),
                 QApplication::translate("QuotesHelper", "Jules Renard") },
               { index++, QApplication::translate("QuotesHelper", "I do not over-intellectualize the production process. I try to keep it simple: Tell the damned story."),
                 QApplication::translate("QuotesHelper", "Tom Clancy") },
               { index++, QApplication::translate("QuotesHelper", "The first sentence can’t be written until the final sentence is written."),
                 QApplication::translate("QuotesHelper", "Joyce Carol Oates") },
               { index++, QApplication::translate("QuotesHelper", "Long patience and application saturated with your heart’s blood — you will either write or you will not — and the only way to find out whether you will or not is to try."),
                 QApplication::translate("QuotesHelper", "Jim Tully, WD") },
               { index++, QApplication::translate("QuotesHelper", "Beware of advice — even this."),
                 QApplication::translate("QuotesHelper", "Carl Sandburg") },
               { index++, QApplication::translate("QuotesHelper", "I would advise anyone who aspires to a writing career that before developing his talent he would be wise to develop a thick hide."),
                 QApplication::translate("QuotesHelper", "Harper Lee") },
               { index++, QApplication::translate("QuotesHelper", "I think the deeper you go into questions, the deeper or more interesting the questions get. And I think that’s the job of art."),
                 QApplication::translate("QuotesHelper", "Andre Dubus III") },
               { index++, QApplication::translate("QuotesHelper", "I don’t need an alarm clock. My ideas wake me."),
                 QApplication::translate("QuotesHelper", "Ray Bradbury, WD") },
               { index++, QApplication::translate("QuotesHelper", "Just write every day of your life. Read intensely. Then see what happens. Most of my friends who are put on that diet have very pleasant careers."),
                 QApplication::translate("QuotesHelper", "Ray Bradbury, WD") },
               { index++, QApplication::translate("QuotesHelper", "Let the world burn through you. Throw the prism light, white hot, on paper."),
                 QApplication::translate("QuotesHelper", "Ray Bradbury, WD") },
               { index++, QApplication::translate("QuotesHelper", "I don’t believe in being serious about anything. I think life is too serious to be taken seriously."),
                 QApplication::translate("QuotesHelper", "Ray Bradbury, WD") },
               { index++, QApplication::translate("QuotesHelper", "It’s none of their business that you have to learn to write. Let them think you were born that way."),
                 QApplication::translate("QuotesHelper", "Ernest Hemingway") },
               { index++, QApplication::translate("QuotesHelper", "When I say work I only mean writing. Everything else is just odd jobs."),
                 QApplication::translate("QuotesHelper", "Margaret Laurence") },
               { index++, QApplication::translate("QuotesHelper", "Do not hoard what seems good for a later place in the book, or for another book; give it, give it all, give it now."),
                 QApplication::translate("QuotesHelper", "Annie Dillard") },
               { index++, QApplication::translate("QuotesHelper", "When writing a novel a writer should create living people; people, not characters. A character is a caricature."),
                 QApplication::translate("QuotesHelper", "Ernest Hemingway") },
               { index++, QApplication::translate("QuotesHelper", "Write while the heat is in you. … The writer who postpones the recording of his thoughts uses an iron which has cooled to burn a hole with."),
                 QApplication::translate("QuotesHelper", "Henry David Thoreau") },
               { index++, QApplication::translate("QuotesHelper", "You can make a movie about anything, as long as it has a hook to hang the advertising on."),
                 QApplication::translate("QuotesHelper", "Roger Corman") },
               { index++, QApplication::translate("QuotesHelper", "A lot of times you get credit for stuff in your movies you didn’t intend to be there."),
                 QApplication::translate("QuotesHelper", "Spike Lee") },
               { index++, QApplication::translate("QuotesHelper", "Get your facts first, then you can distort them as you please."),
                 QApplication::translate("QuotesHelper", "Mark Twain") },
               { index++, QApplication::translate("QuotesHelper", "Feydeau’s one rule of playwriting: Character A: My life is perfect as long as I don’t see Character B. Knock Knock. Enter Character B."),
                 QApplication::translate("QuotesHelper", "John Guare") }};
    if (_index == -1) {
        _index = QRandomGenerator::global()->bounded(0, quotes.size());
    }
    return quotes[_index];
}
