name: Build Starc for Mac

env:
  APP_VERSION: 0.8.3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  create:
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build_mac_qt5:
    name: Build Mac OS X version with qt5
    runs-on: macos-15-intel
    timeout-minutes: 120
    steps:
      - name: Checkout sources for push or create tag event
        if: github.event_name != 'pull_request'
        uses: actions/checkout@master
        with:
          token: ${{ secrets.ACTION_RUNNER }}
          submodules: recursive
          fetch-depth: 0

      - name: Checkout sources for pull request event
        if: github.event_name == 'pull_request'
        uses: actions/checkout@master

      - name: Checkout submodules for pull request event
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          git submodule update --init --recursive src/3rd_party/pdfhummus/ src/3rd_party/pdftextextraction/

      - name: Add info about dev build to the env
        shell: bash
        run: |
          DEV_BUILD=$(git rev-list `git rev-list --tags --no-walk --max-count=1`..HEAD --count)
          echo "DEV_BUILD=$DEV_BUILD" >> $GITHUB_ENV
          if [ "$DEV_BUILD" -gt "0" ]; then
            echo "BUGSPLAT_VERSION=${{env.APP_VERSION}} dev $DEV_BUILD-qt5" >> $GITHUB_ENV
          else
            echo "BUGSPLAT_VERSION=${{env.APP_VERSION}}-qt5" >> $GITHUB_ENV
          fi

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.15.2
          target: desktop

      - name: Build crashpad
        shell: bash
        run: |
          cd build
          chmod +x ./build_crashpad.sh
          ./build_crashpad.sh

      - name: Run QMake
        shell: bash
        run: |
          cd src
          qmake starc.pro DEFINES+="DEV_BUILD=$DEV_BUILD"

      - name: Build
        shell: bash
        run: |
          cd src
          make -j4

      - name: Upload debug symbols
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          curl -sL -O "https://app.bugsplat.com/download/symbol-upload-macos-intel"
          xattr -r -d com.apple.quarantine ./symbol-upload-macos-intel || true
          chmod +x symbol-upload-macos-intel
          ./symbol-upload-macos-intel \
            -b "${{ secrets.BUGSPLAT_DATABASE }}" \
            -a "starcapp-mac" \
            -v "${{ env.BUGSPLAT_VERSION }}" \
            -d "src/_build" \
            -f "**/*.dSYM" \
            -i "${{ secrets.BUGSPLAT_USER }}" \
            -s "${{ secrets.BUGSPLAT_PASSWORD }}" \
            -m

      - name: Make dmg image
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          retry_on: error
          shell: bash
          command: |
            cd build/mac
            ./create_dmg.sh ${{env.APP_VERSION}}
            mv starc-setup.dmg starc-setup-qt5.dmg
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_APP_PASSWORD: ${{ secrets.APPLE_ID_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Collect artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac packages with qt5
          path: build/mac/starc-setup-qt5.dmg

      - name: Publish artifacts to the dev stream and notify clients
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') != true && github.ref == 'refs/heads/master'
        shell: bash
        run: |
          curl -F "api_key=${{ secrets.STARC_API_KEY }}" -F "name_for_file=starc-setup-qt5.dmg" -F "file_bin=@build/mac/starc-setup-qt5.dmg" https://starc.app/api/app/updates/publish/

      - name: Publish artifacts to the GitHub releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/mac/starc-setup-qt5.dmg

  build_mac_qt6:
    name: Build Mac OS X version with qt6
    runs-on: macos-15
    timeout-minutes: 120
    steps:
      - name: Checkout sources for push or create tag event
        if: github.event_name != 'pull_request'
        uses: actions/checkout@master
        with:
          token: ${{ secrets.ACTION_RUNNER }}
          submodules: recursive
          fetch-depth: 0

      - name: Checkout sources for pull request event
        if: github.event_name == 'pull_request'
        uses: actions/checkout@master

      - name: Checkout submodules for pull request event
        if: github.event_name == 'pull_request'
        shell: bash
        run: |
          git submodule update --init --recursive src/3rd_party/pdfhummus/ src/3rd_party/pdftextextraction/

      - name: Add info about dev build to the env
        shell: bash
        run: |
          DEV_BUILD=$(git rev-list `git rev-list --tags --no-walk --max-count=1`..HEAD --count)
          echo "DEV_BUILD=$DEV_BUILD" >> $GITHUB_ENV
          if [ "$DEV_BUILD" -gt "0" ]; then
            echo "BUGSPLAT_VERSION=${{env.APP_VERSION}} dev $DEV_BUILD-qt6" >> $GITHUB_ENV
          else
            echo "BUGSPLAT_VERSION=${{env.APP_VERSION}}-qt6" >> $GITHUB_ENV
          fi

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.10.3
          target: desktop
          modules: 'qt5compat qtmultimedia qtspeech qtwebsockets'

      - name: Build crashpad
        shell: bash
        run: |
          cd build
          chmod +x ./build_crashpad.sh
          ./build_crashpad.sh -u

      - name: Run QMake
        shell: bash
        run: |
          cd src
          qmake starc.pro QMAKE_APPLE_DEVICE_ARCHS="x86_64 arm64" CRASHPAD_ARCH=universal DEFINES+="DEV_BUILD=$DEV_BUILD"

      - name: Build
        shell: bash
        run: |
          cd src
          make -j4

      - name: Set up Node.js for symbol upload
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dump_syms
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        run: |
          npm i -g @mapbox/node-pre-gyp
          npm i -g node-dump-syms

      - name: Upload debug symbols
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
        uses: BugSplat-Git/symbol-upload@v11
        with:
          clientId: ${{ secrets.BUGSPLAT_USER }}
          clientSecret: ${{ secrets.BUGSPLAT_PASSWORD }}
          database: ${{ secrets.BUGSPLAT_DATABASE }}
          application: starcapp-mac
          version: ${{ env.BUGSPLAT_VERSION }}
          directory: src/_build
          files: "**/*.dSYM"
          dumpSyms: true
          node-version: 24

      - name: Make dmg image
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          retry_on: error
          shell: bash
          command: |
            cd build/mac
            ./create_dmg.sh ${{env.APP_VERSION}}
        env:
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_APP_PASSWORD: ${{ secrets.APPLE_ID_APP_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

      - name: Collect artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac packages with qt6
          path: build/mac/starc-setup.dmg

      - name: Publish artifacts to the dev stream and notify clients
        if: github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') != true && github.ref == 'refs/heads/master'
        shell: bash
        run: |
          curl -F "api_key=${{ secrets.STARC_API_KEY }}" -F "name_for_file=starc-setup.dmg" -F "file_bin=@build/mac/starc-setup.dmg" https://starc.app/api/app/updates/publish/
          curl -F "api_key=${{ secrets.STARC_API_KEY }}" -F "system=mac" -F "qt=6" -F "version=${{env.APP_VERSION}} dev ${{env.DEV_BUILD}}" https://starc.app/api/app/updates/notify/

      - name: Publish artifacts to the GitHub releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/mac/starc-setup.dmg
